### ISSUE TITLE
ReViT-S

### ISSUE THREAD

**Issue by FengyunZuo** [ADiko1997/ReViT#1]
Hello, is there a pre-trained model of ReViT-s available on ImageNet-1k?

**Comment by ADiko1997** [comment]
Hi, no we only train on ReViT-B.

**Comment by ADiko1997** [comment]
Closing the issue.

**Comment by FengyunZuo** [comment]
ok, Thank you.发自我的平板-------- 原始邮件 --------发件人： Anxhelo ***@***.***>日期： 2024年3月30日周六 晚上9:20收件人： ADiko1997/ReViT ***@***.***>抄送： Ningyi ***@***.***>, Author ***@***.***>主    题： Re: [ADiko1997/ReViT] ReViT-S (Issue #1)
Closed #1 as completed.
